# GitHub Actions workflow for Baler (BAd Link reportER) version 0.0.0.
# This is available as the file "sample-workflow.yml" from the source
# repository for Baler at https://github.com/caltechlibrary/baler/.

name: "Bad Link Reporter"

# Configure this section ─────────────────────────────────────────────

env:
  # Files examined by the workflow:
  files: '*.md'
  # Optional file containing a list of URLs to ignore, one per line:
  ignore: '.github/workflows/ignored-urls.txt'
  # Label assigned to issues created by this workflow:
  labels: 'bug'

on:
  schedule:
    - cron: "00 11 * * *"
  pull_request:
    paths: ['**.md']
  push:
    paths:
      - .github/workflows/bad-link-reporter.yml
      - .github/workflows/ignored-urls.txt
  workflow_dispatch:
    inputs:
      debug:
        description: "Run unconditionally in debug mode"
        type: boolean

# The rest of this file should be left as-is ─────────────────────────

run-name: Test links in files
jobs:
  run-baler:
    name: Run Bad Link Reporter
    runs-on: ubuntu-latest
    steps:
      - uses: mhucka/baler@main
        with:
          files:  ${{github.event.inputs.files  || env.files}}
          labels: ${{github.event.inputs.labels || env.labels}}
          ignore: ${{github.event.inputs.ignore || env.ignore}}
          debug:  ${{github.event.inputs.debug  || env.debug}}
